import type { NextPage } from 'next'
import Head from 'next/head'
import HeroSection from '../components/HeroSection/Index'
import '../styles/Home.module.css'
import Form from '../components/Form'
import ImageSection from '../components/ImageSection/ImageSection'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>On Spot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageSection />
      <HeroSection/>
      {/* <Form /> */}
    </div>
  )
}

export default Home
